### ISSUE TITLE
How to get the camera pose during mapping (rather than tracking)?

### ISSUE THREAD

**Issue by bairuofei** [ljjTYJR/HF-SLAM#1]
Hi, very interesting work.

May I ask how to get the camera pose during mapping? In Sec. IV-B of your Arxiv paper, you mentioned that "we initialize the camera pose assuming constant camera velocity," which means the initial camera pose may have some errors. If so, how can this not-well-posed RGBD image be used to optimize the 3D GS model?

Or you just do tracking first to correct the camera pose, and then do mapping to optimize the 3D GS model?

Thank you and looking forward to your reply.

**Comment by ljjTYJR** [comment]
Hi,

Here is a quick answer:
So, during the online mapping process, the mapping and tracking are conducted alternately.
We assume an initial guess of the camera pose by the constant velocity model and then do tracking to refine the camera pose.

I am sorry I have not released the code before the IROS :(, I am very busy preparing a paper targeted at CVPR, so I may not upload the code in the recent month. But I would be happy to answer any question
.

**Comment by bairuofei** [comment]
Thanks for your reply. So it means, in tracking process, you only refine the camera pose; and in mapping process, you use the refined camera pose to update the GS model (in which the camera pose will not be further optimized). Is it right?

**Comment by ljjTYJR** [comment]
Yes

**Comment by bairuofei** [comment]
Got it, thanks for your reply!
